[env:adafruit_feather_rp2040]
; Use the community-maintained platform you linked
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
; The Internal ID in this repo is 'adafruit_feather', not 'adafruit_feather_rp2040'
board = adafruit_feather
framework = arduino
build_src_filter = +<*> -<main_lora.cpp>


[env:adafruit_feather_m0_lora]
platform = atmelsam
board = adafruit_feather_m0
framework = arduino
lib_deps = 
    mikem/RadioHead @ ^1.120.0
build_src_filter = +<*> -<main_lora.cpp>